#!/bin/bash

# uart connection:
# picocom -b 921600 /dev/ttyUSB0 --imap spchex,lfcrlf
# tio -b 921600 /dev/ttyUSB0 -m INLCRNL

# generate whole firmware for air101/103:
# cp AIR[101|103].fls final.fls
# cat script-for-air[101|103].img >>final.fls
# rm -f script.img script.bin


# which dir this script at.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

usage()
{
  echo "Generate air101/103 script.img or esp32 script.bin for LuatOS."
  echo "Usage: luatos-gen-script-img [air101|air103|esp32] src_dir"
}

if [ ! -f "$SCRIPT_DIR/luatos-luac" ] && [ ! -f "$SCRIPT_DIR/luatos-mkscriptbin" ] && [ ! -f "$SCRIPT_DIR/luatos-wm_tool" ]; then
  echo "Please build luatos-luac & luatos-mkscriptbin & luatos-wm_tool first."
  exit
fi

# if no args
if [ $# -ne 2 ]; then
  echo "Error: wrong arguments"
  usage
  exit
fi

# if arg2 is not exist or not a dir
if [ ! -d "$2" ]; then
  echo "Error : source dir not exist."
  echo "Please create a dir and put lua sources and other resources in it."
  exit
fi

# compile all lua sources in src dir to disk dir,
# and copy all resources in src dir to disk dir.
TARGET_DIR=$(mktemp -d)
SOURCE_DIR="$2"

# filename for target script.img or script.bin 
TARGET_FIRMWARE_FILENAME=script-"$(basename $SOURCE_DIR)"-"$1"

rm -rf $TARGET_DIR && mkdir $TARGET_DIR

for i in `ls $SOURCE_DIR`; do
  if [[ "$i" = *.lua ]]; then
    FILENAME_NO_SUF=$(basename -s .lua $i)
    $SCRIPT_DIR/luatos-luac -s -o $TARGET_DIR/$FILENAME_NO_SUF.luac $SOURCE_DIR/$i
  else
    cp $SOURCE_DIR/$i $TARGET_DIR/
  fi
done

# command exit status
RET=
# generate script.bin file
$SCRIPT_DIR/luatos-mkscriptbin $TARGET_DIR
RET=$?

if [ "$RET" -ne "0" ]; then
	echo "luatos-mkscriptbin failed !"
	exit
fi

case "$1" in
  "air101" ) 
    echo -n "Generate $TARGET_FIRMWARE_FILENAME.img "
    $SCRIPT_DIR/luatos-wm_tool -b script.bin -it 1 -fc 0 -ih 20008000 -ra 81E0000 -ua 0 -nh 0  -un 0 -o "$TARGET_FIRMWARE_FILENAME" >/dev/null
    RET=$?
    rm -f script.bin
    ;;
  "air103" ) 
    echo -n "Generate $TARGET_FIRMWARE_FILENAME.img "
    $SCRIPT_DIR/luatos-wm_tool -b script.bin -it 1 -fc 0 -ih 20008000 -ra 80E0000 -ua 0 -nh 0  -un 0 -o $TARGET_FIRMWARE_FILENAME >/dev/null
    RET=$?
    rm -f script.bin
    ;;
  "esp32" )  
    echo -n "Genereate $TARGET_FIRMWARE_FILENAME.img " 
    mv script.bin "$TARGET_FIRMWARE_FILENAME.img"
    RET=$?
    ;;
  * )  
    echo "Error: only support air101 / air103 / esp32"
    RET=1
    exit
    ;;
esac

if [ "$RET" -eq "0" ]
then
  echo "[done]"
  echo "It can be programmed by luatos-flash-script-img."
else
  echo "[failed]"
fi

