#!/bin/bash

# which dir this script at.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

usage()
{
  echo "Flash air101/103 script.img or esp32c3/s3 script.bin to target device."
  echo "Usage: luatos-flash-script-img [air101|air103|esp32c3|esp32s3] <script.[img|bin]>"
}

# if no args
if [ $# -ne 2 ]; then
  usage
  exit
fi

check_wm_tool()
{
  if [ ! -f "$SCRIPT_DIR/luatos-wm_tool" ]; then
    echo "please build luatos-wm_tool first."
    exit
  fi
}

check_esptool()
{
  if ! [ -x "$(command -v esptool.py)" ]; then
    echo "please install esptool.py first."
    exit
  fi
}

FIRMWARE="$2"

if [ ! -f $FIRMWARE ]; then
  echo "Error: $FIRMWARE not exist."
  exit
fi

case "$1" in
  "air101" )
    check_wm_tool
    $SCRIPT_DIR/luatos-wm_tool -it 1 -fc 0 -ih 20008000 -ra 81E0000 -ua 0 -nh 0  -un 0 -ds 2M -c ttyUSB0 -ws 115200 -rs rts -dl $FIRMWARE 
    ;;
  "air103" )
    check_wm_tool
    $SCRIPT_DIR/luatos-wm_tool -it 1 -fc 0 -ih 20008000 -ra 80E0000 -ua 0 -nh 0  -un 0 -ds 2M -c ttyUSB0 -ws 115200 -rs rts -dl $FIRMWARE
    ;;
  "esp32s3" )
    check_esptool
    esptool.py write_flash 0xF90000 $FIRMWARE 
    ;;
  "esp32c3" )
    check_esptool
    esptool.py write_flash 0x390000 $FIRMWARE 
    ;;
  * )
    echo "Error: only support air101 / air103 / esp32s3 / esp32c3."
    exit
    ;;
esac

echo "Done. you may need reset the target device."
