#!/bin/bash

# which dir this script at.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

usage()
{
  echo "Flash LuatOS soc firmware to target device."
  echo "Usage: luatos-flash-soc <.soc firmware>"
}



# if no args
if [ $# -ne 1 ]; then
  echo "Error : please specify LuatOS soc file for AIR101/103 or ESP32S3/C3"
  usage
  exit
fi

# soc file to be flashed
SOC_FILE="$1"
# tmp dir to extract soc to
TMP_DIR=$(mktemp -d)
# info.json should alway exist
INFO_JSON="$TMP_DIR"/info.json

# extract it
7za -bso0 -bsp0 -aoa x "$SOC_FILE" -o"$TMP_DIR"
RET=$?

if [ "$RET" -ne "0" ]; then
  echo "Error: extract soc file failed."
  exit
fi

if [ ! -f "$INFO_JSON" ]; then
  echo "Error : wrong soc file."
  exit
fi

# try to detect esp32 first
CHIP_TYPE=$(grep -o '"type": "[^"]*' "$INFO_JSON" | grep -o '[^"]*$' | head -n 1)

# if not esp32, it's air101 or 103
if [ "$CHIP_TYPE""x" == "x" ]; then
  if grep -q AIR101.fls "$INFO_JSON"; then
    CHIP_TYPE=air101
  elif grep -q AIR103.fls "$INFO_JSON"; then    
    CHIP_TYPE=air103
  fi
fi

# if not air101 and 103, then exit
if [ "$CHIP_TYPE""x" == "x" ]; then
  echo "Error : soc file not supported."
  exit
fi


check-wm_tool()
{
  if [ ! -f "$SCRIPT_DIR/luatos-wm_tool" ]; then
    echo "please build luatos-wm_tool first."
    exit
  fi
}

check-esptool()
{
  if ! [ -x "$(command -v esptool.py)" ]; then
    echo "please install esptool.py first."
    exit
  fi
}

check-fileexist()
{
  FILE="$1"
  if [ ! -f "$FILE" ]; then
    echo "Error: $FILE not exist"
    exit
  fi
}

case "$CHIP_TYPE" in
  "air101" )
    check-wm_tool
    check-fileexist "$TMP_DIR"/AIR101.fls
    "$SCRIPT_DIR"/luatos-wm_tool -ds 2M -c ttyUSB0 -ws 115200 -rs rts -dl "$TMP_DIR"/AIR101.fls
    ;;
  "air103" )
    check-wm_tool
    check-fileexist "$TMP_DIR"/AIR103.fls
    "$SCRIPT_DIR"/luatos-wm_tool -ds 2M -c ttyUSB0 -ws 115200 -rs rts -dl "$TMP_DIR"/AIR103.fls
    ;;
  "esp32" )
    check-esptool
    check-fileexist "$TMP_DIR"/bootloader.bin
    check-fileexist "$TMP_DIR"/partition-table.bin
    check-fileexist "$TMP_DIR"/luatos.bin
    esptool.py write_flash 0x0000 "$TMP_DIR"/bootloader.bin 0x8000 "$TMP_DIR"/partition-table.bin 0x10000 "$TMP_DIR"/luatos.bin 
    ;;
   * )
    echo "Error: soc file not supported"
    exit
    ;;
esac

rm -rf "$TMP_DIR"
echo "Done"
