#!/bin/bash

# which dir this script at.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

usage()
{
  echo "Flash air101/103 script.img to target device."
  echo "Usage: luatos-flash-script-img [air101|air103] <script.img>"
}

if [ ! -f "$SCRIPT_DIR/luatos-wm_tool" ]; then
  echo "please build luatos-wm_tool first."
  exit
fi

# if no args
if [ $# -ne 2 ]; then
  usage
  exit
fi

# if not air101 and air103
if [ "$1" != "air101" ] && [ "$1" != "air103" ]; then
  usage
  exit
fi

FIRMWARE="$2"
if [ "$1""x" == "air101""x" ]; then
  $SCRIPT_DIR/luatos-wm_tool -it 1 -fc 0 -ih 20008000 -ra 81E0000 -ua 0 -nh 0  -un 0 -ds 2M -c ttyUSB0 -ws 115200 -rs rts -dl $FIRMWARE 
elif [ "$1""x" == "air103""x" ]; then
  $SCRIPT_DIR/luatos-wm_tool -it 1 -fc 0 -ih 20008000 -ra 80E0000 -ua 0 -nh 0  -un 0 -ds 2M -c ttyUSB0 -ws 115200 -rs rts -dl $FIRMWARE
fi

echo "Done, you may need reset the target device."
