#!/bin/bash

# uart connection:
# picocom -b 921600 /dev/ttyUSB0 --imap spchex,lfcrlf
# tio -b 921600 /dev/ttyUSB0 -m INLCRNL

# generate whole firmware:
# cp AIR[101|103].fls final.fls
# cat script-for-air[101|103].img >>final.fls
# rm -f script.img script.bin


# which dir this script at.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

usage()
{
  echo "Generate air101/103 script.img or esp32 script.bin for LuatOS."
  echo "Usage: luatos-gen-script-img [air101|air103|esp32] src_dir"
}

if [ ! -f "$SCRIPT_DIR/luatos-luac" ] && [ ! -f "$SCRIPT_DIR/luatos-mkscriptbin" ] && [ ! -f "$SCRIPT_DIR/luatos-wm_tool" ]; then
  echo "please build luatos-luac & luatos-mkscriptbin & luatos-wm_tool first."
  exit
fi

# if no args
if [ $# -ne 2 ]; then
  echo "Error: wrong arguments"
  usage
  exit
fi

# if not air101 / air103 / esp32
if [ "$1" != "air101" ] && [ "$1" != "air103" ] && [ "$1" != "esp32" ]; then
  echo "Error: only support air101 / air103 / esp32"
  usage
  exit
fi 

if [ ! -d "$2" ]; then
  echo "Error : source dir not exist."
  usage
  exit
fi

# compile all lua sources in src dir to disk dir,
# and copy all resources in src dir to disk dir.
TARGET_DIR=$(mktemp -d)
SOURCE_DIR="$2"

# filename for target script.img or script.bin 
TARGET_FIRMWARE_FILENAME=$(basename $SOURCE_DIR)

if [ ! -d $SOURCE_DIR ]; then 
  echo "Error: $SOURCE_DIR not exist."
  echo "you should create a dir and put lua sources and other resources in it."
  exit
fi

rm -rf $TARGET_DIR && mkdir $TARGET_DIR

for i in `ls $SOURCE_DIR`; do
  if [[ "$i" = *.lua ]]; then
    FILENAME_NO_SUF=$(basename -s .lua $i)
    $SCRIPT_DIR/luatos-luac -s -o $TARGET_DIR/$FILENAME_NO_SUF.luac $SOURCE_DIR/$i
  else
    cp $SOURCE_DIR/$i $TARGET_DIR/
  fi
done

# generate script.bin file
$SCRIPT_DIR/luatos-mkscriptbin $TARGET_DIR

if [ ! -f "./script.bin" ]; then
	echo "Generate script.bin failed !"
	exit
fi

# generate script.img file for AIR101
if [ "$1""x" == "air101""x" ]; then
  $SCRIPT_DIR/luatos-wm_tool -b script.bin -it 1 -fc 0 -ih 20008000 -ra 81E0000 -ua 0 -nh 0  -un 0 -o "script-"$TARGET_FIRMWARE_FILENAME"-air101"
  rm -f script.bin
  echo "script-$TARGET_FIRMWARE_FILENAME-air101.img generated."
  echo ""
  echo "It can be programmed by:"
  echo "luatos-flash-script-img air101 script-$TARGET_FIRMWARE_FILENAME-air101.img"
elif [ "$1""x" == "air103""x" ]; then
  $SCRIPT_DIR/luatos-wm_tool -b script.bin -it 1 -fc 0 -ih 20008000 -ra 80E0000 -ua 0 -nh 0  -un 0 -o "script-"$TARGET_FIRMWARE_FILENAME"-air103" 
  rm -f script.bin
  echo "script-$TARGET_FIRMWARE_FILENAME-air103.img generated."
  echo "It can be programmed by:"
  echo ""
  echo "luatos-flash-script-img air103 script-$TARGET_FIRMWARE_FILENAME-air103.img"
elif [ "$1""x" == "esp32""x" ]; then
  mv script.bin "script-"$TARGET_FIRMWARE_FILENAME"-esp32.bin"
  echo "script.bin generated."
  echo "It can be programmed by:"
  echo ""
  echo "luatos-flash-script-img [esp32s3|esp32c3] script-$TARGET_FIRMWARE_FILENAME-esp32.bin"
fi
rm -rf $TARGET_DIR 
exit

