#!/bin/bash

# which dir this script at.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

usage()
{
  echo "Flash air101/103 base firmware to target device."
  echo "Usage: luatos-flash-base-firmware <base firmware for air101/103>"
}

if [ ! -f "$SCRIPT_DIR/luatos-wm_tool" ]; then
  echo "please build luatos-wm_tool first."
  exit
fi

# if no args
if [ $# -ne 1 ]; then
  usage
  exit
fi

FIRMWARE="$1"
$SCRIPT_DIR/luatos-wm_tool -ds 2M -c ttyUSB0 -ws 115200 -rs rts -dl $FIRMWARE
